function(society_add_app_icons target)
    set(icons "${CMAKE_CURRENT_SOURCE_DIR}/resources/Appicon/generated")
    if(NOT EXISTS "${icons}/manifest.json")
        message(FATAL_ERROR "Society icons are missing. Run tools/generate_app_icons.py with Pillow.")
    endif()
    if(APPLE AND NOT IOS)
        set(runtime_icon "${icons}/macos/Society.png")
    else()
        set(runtime_icon "${icons}/common/Society.png")
    endif()
    set_source_files_properties("${runtime_icon}" PROPERTIES QT_RESOURCE_ALIAS "Society.png")
    qt_add_resources(${target} society_branding PREFIX "/branding" FILES "${runtime_icon}")

    if(IOS)
        set(catalog "${icons}/ios/Assets.xcassets")
        target_sources(${target} PRIVATE "${catalog}")
        set_source_files_properties("${catalog}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
        set_target_properties(${target} PROPERTIES
            XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME AppIcon)
    elseif(APPLE)
        set(icon "${icons}/macos/Society.icns")
        target_sources(${target} PRIVATE "${icon}")
        set_source_files_properties("${icon}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
        set_target_properties(${target} PROPERTIES MACOSX_BUNDLE_ICON_FILE Society.icns)
    elseif(ANDROID)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${icons}/manifest.json")
        get_target_property(package ${target} QT_ANDROID_PACKAGE_SOURCE_DIR)
        if(NOT package OR NOT EXISTS "${package}/AndroidManifest.xml")
            message(FATAL_ERROR "Configure Society's Android provider before its icons")
        endif()
        file(COPY "${icons}/android/res/" DESTINATION "${package}/res")
        file(READ "${package}/AndroidManifest.xml" manifest)
        string(REGEX REPLACE " android:(icon|roundIcon)=\"[^\"]*\"" "" manifest "${manifest}")
        string(REPLACE "<application " "<application android:icon=\"@mipmap/ic_launcher\" android:roundIcon=\"@mipmap/ic_launcher_round\" " manifest "${manifest}")
        file(WRITE "${package}/AndroidManifest.xml" "${manifest}")
    elseif(WIN32)
        enable_language(RC)
        set(SOCIETY_WINDOWS_ICON "${icons}/windows/Society.ico")
        configure_file("${CMAKE_CURRENT_SOURCE_DIR}/platform/windows/Society.rc.in"
            "${CMAKE_CURRENT_BINARY_DIR}/Society-icon.rc" @ONLY)
        target_sources(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/Society-icon.rc")
        set_property(SOURCE "${CMAKE_CURRENT_BINARY_DIR}/Society-icon.rc" APPEND PROPERTY OBJECT_DEPENDS "${SOCIETY_WINDOWS_ICON}")
    elseif(EMSCRIPTEN)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND "${CMAKE_COMMAND}" "-DSOCIETY_WEB_OUTPUT=$<TARGET_FILE_DIR:${target}>"
                "-DSOCIETY_WEB_ICONS=${icons}/web" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/WebIcons.cmake"
            VERBATIM)
    elseif(UNIX)
        include(GNUInstallDirs)
        install(DIRECTORY "${icons}/linux/hicolor/" DESTINATION "${CMAKE_INSTALL_DATADIR}/icons/hicolor")
        install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/platform/linux/com.iisacc.society.desktop"
            DESTINATION "${CMAKE_INSTALL_DATADIR}/applications")
        install(TARGETS ${target} RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    endif()
endfunction()
