# Register the shared SDK's Society URL with each native application package.
function(society_add_application_links target)
    if(APPLE)
        get_target_property(plist ${target} MACOSX_BUNDLE_INFO_PLIST)
        if(NOT plist OR NOT EXISTS "${plist}")
            set(plist "${CMAKE_ROOT}/Modules/MacOSXBundleInfo.plist.in")
        endif()
        file(READ "${plist}" contents)
        string(FIND "${contents}" "<dict>" root_dict)
        if(root_dict LESS 0)
            message(FATAL_ERROR "The Society Info.plist has no root dictionary")
        endif()
        math(EXPR insertion "${root_dict} + 6")
        string(SUBSTRING "${contents}" 0 ${insertion} before)
        string(SUBSTRING "${contents}" ${insertion} -1 after)
        set(url_types "\n<key>CFBundleURLTypes</key><array><dict><key>CFBundleURLName</key><string>com.iisacc.society</string><key>CFBundleURLSchemes</key><array><string>society</string></array></dict></array>\n")
        set(output "${CMAKE_CURRENT_BINARY_DIR}/Society-ApplicationLinks.plist.in")
        file(WRITE "${output}" "${before}${url_types}${after}")
        set_target_properties(${target} PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${output}")
    elseif(ANDROID)
        get_target_property(package ${target} QT_ANDROID_PACKAGE_SOURCE_DIR)
        file(READ "${package}/AndroidManifest.xml" manifest)
        set(filter "<intent-filter><action android:name=\"android.intent.action.VIEW\"/><category android:name=\"android.intent.category.DEFAULT\"/><category android:name=\"android.intent.category.BROWSABLE\"/><data android:scheme=\"society\" android:host=\"generation-history\"/></intent-filter>")
        string(REPLACE "</activity>" "${filter}</activity>" manifest "${manifest}")
        file(WRITE "${package}/AndroidManifest.xml" "${manifest}")
    endif()
endfunction()
