# Preserve the app's existing Qt/File Provider plist and add local-network purpose.
function(society_add_network_privacy target)
    get_target_property(original "${target}" MACOSX_BUNDLE_INFO_PLIST)
    if(NOT original OR original MATCHES "-NOTFOUND$")
        set(original "${CMAKE_ROOT}/Modules/MacOSXBundleInfo.plist.in")
    endif()
    file(READ "${original}" contents)
    string(FIND "${contents}" "<dict>" position)
    if(position LESS 0)
        message(FATAL_ERROR "The Society Info.plist has no root dictionary")
    endif()
    math(EXPR position "${position} + 6")
    string(SUBSTRING "${contents}" 0 ${position} prefix)
    string(SUBSTRING "${contents}" ${position} -1 suffix)
    set(output "${CMAKE_CURRENT_BINARY_DIR}/Society-Network.Info.plist.in")
    set(camera "")
    if(IOS)
        set(camera "<key>NSCameraUsageDescription</key><string>Society uses the camera to scan the pairing QR code displayed on your desktop. Camera images are not saved or uploaded.</string>\n")
    endif()
    set(group "")
    if(NOT IOS)
        set(group "<key>SocietyAppGroup</key><string>${SOCIETY_MAC_APP_GROUP}</string>\n")
    endif()
    file(WRITE "${output}" "${prefix}\n<key>NSLocalNetworkUsageDescription</key><string>Society discovers your signed-in devices and connects to them to access your container files on the local network.</string>\n<key>NSBonjourServices</key><array><string>_society-pair._udp</string></array>\n${group}${camera}${suffix}")
    set_target_properties("${target}" PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${output}")
endfunction()
