# Preserve the app's existing Qt/File Provider plist and add local-network purpose.
function(society_add_network_privacy target)
    get_target_property(original "${target}" MACOSX_BUNDLE_INFO_PLIST)
    if(NOT original OR original MATCHES "-NOTFOUND$")
        set(original "${CMAKE_ROOT}/Modules/MacOSXBundleInfo.plist.in")
    endif()
    file(READ "${original}" contents)
    string(FIND "${contents}" "<dict>" position)
    if(position LESS 0)
        message(FATAL_ERROR "The Society Info.plist has no root dictionary")
    endif()
    math(EXPR position "${position} + 6")
    string(SUBSTRING "${contents}" 0 ${position} prefix)
    string(SUBSTRING "${contents}" ${position} -1 suffix)
    set(output "${CMAKE_CURRENT_BINARY_DIR}/Society-Network.Info.plist.in")
    set(camera "")
    set(photos "<key>NSPhotoLibraryUsageDescription</key><string>Society synchronizes photos and videos between your device photo library and your Society devices. Originals remain in the photo library.</string>\n<key>NSPhotoLibraryAddUsageDescription</key><string>Society saves photos and videos received from your Society devices to your photo library.</string>\n")
    if(IOS)
        set(camera "<key>NSCameraUsageDescription</key><string>Society uses the camera to scan the pairing QR code displayed on your desktop. Camera images are not saved or uploaded.</string>\n")
        string(APPEND camera "<key>UIBackgroundModes</key><array><string>processing</string></array>\n<key>BGTaskSchedulerPermittedIdentifiers</key><array><string>com.iisacc.society.sync.*</string></array>\n")
    endif()
    set(group "")
    set(bluetooth "<key>NSBluetoothAlwaysUsageDescription</key><string>Society uses Bluetooth to discover nearby Society devices and exchange connection information. Files transfer over Wi-Fi or LAN.</string>\n")
    if(NOT IOS)
        set(group "<key>SocietyAppGroup</key><string>${SOCIETY_MAC_APP_GROUP}</string>\n")
    endif()
    file(WRITE "${output}" "${prefix}\n<key>NSLocalNetworkUsageDescription</key><string>Society discovers your signed-in devices and connects to them to access your container files on the local network.</string>\n<key>NSBonjourServices</key><array><string>_society-pair._udp</string></array>\n${group}${camera}${photos}${bluetooth}${suffix}")
    set_target_properties("${target}" PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${output}")
endfunction()
