if(NOT EXISTS "${SOCIETY_WEB_OUTPUT}/Society.html")
    message(FATAL_ERROR "Qt's generated Society.html is required for web icon integration")
endif()
file(COPY "${SOCIETY_WEB_ICONS}/" DESTINATION "${SOCIETY_WEB_OUTPUT}")
file(READ "${SOCIETY_WEB_OUTPUT}/Society.html" page)
if(NOT page MATCHES "<!-- Society app icons -->")
    string(REPLACE "</head>" "<!-- Society app icons -->\n<link rel=\"icon\" href=\"favicon.ico\">\n<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n<link rel=\"manifest\" href=\"manifest.webmanifest\">\n<meta name=\"theme-color\" content=\"#082014\">\n</head>" page "${page}")
    file(WRITE "${SOCIETY_WEB_OUTPUT}/Society.html" "${page}")
endif()
